---
title: "課?<a0>?練習模<e7><89><88>"
author: "selu"
date: "2020-12-12"
output: output_format
params:
  id: "410973065"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-10","11-15"), 15, replace=T)
ages_chr
unique(ages_chr)
table(ages_chr)
```

```{r}
library(stringr)
library(glue)
thatsAlright <- 
  jsonlite::fromJSON(
    "https://www.dropbox.com/s/f3ox7rd5favr0o0/thatsAlright.json?dl=1"
```


```{r}
)
View(thatsAlright)
```

```{r}
# 字串向量長度
length(c("I will"))
# 每個元素值有幾個字元(包含符號與空格)
str_length(c("I will"))
line67 <- thatsAlright[c(6,7)]
line67
```
```{r}
str_split(line67, ",")
```
```{r}
# 'you'是否出現在第1,2,3,...最後一句
pick_you <- str_detect(thatsAlright, pattern="you")
str_view_all(thatsAlright[pick_you],"you")
```
```{r}
# 哪幾句有'you'出現
whichHas_you <- str_which(thatsAlright, pattern="you")
whichHas_you
str_view_all(thatsAlright[whichHas_you],"you")
```
```{r}
whichHas_you_fromPick <- which(pick_you)
whichHas_you_fromPick
```
```{r}
# 只留下有出現'you'字眼的句子
onlyYou <- str_subset(thatsAlright, pattern="you")

length(thatsAlright)
length(onlyYou)
onlyYou
```
```{r}
# 每一句有幾個"you"
countEach_you <- str_count(thatsAlright,
                           pattern="you")
countEach_you
str_view_all(
  thatsAlright[1:10], pattern="you")
```
```{r}
patternWithBoundary="\\byou\\b"
str_view_all(
  c("I am yours",
    "And you?",
    "Young and smart", 
    "It means that you and I are lucky"),
  pattern="you"
)
```
```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")
SchoolIds <- c("410973029", "410988011", "410974023","410783025","710773022","410788021","410673124","410873051","49988001")
```

```{r}
Rmdfiles
regexPattern="[Rr][Mm][Dd]"
str_subset(
  Rmdfiles, pattern=regexPattern)
```
```{r}
SchoolIds
regexPattern="[4](108|109)(73|88)"
str_subset(
  SchoolIds, pattern=regexPattern)
```
```{r}
sameIdentities <- c("臺北市", "台北市", "台北大學", "臺北大學", "基隆市")

str_detect(
  sameIdentities, pattern="[台臺]")
str_view_all(
  sameIdentities, pattern="[台臺]")
```
```{r}
str_extract(
  sameIdentities, pattern="[台臺]北市")
```

```{r}
dragonPeople <-
  c(
    "住在台北市的臺北人也常被稱為天龍人")
str_extract(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
# 當一個元素值內的文字規律可多次出現時用_all來一網打盡，否則只處理第一個出現的規律
str_extract_all(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
```
```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = rep("[Rr][Mm][Dd]",5),
  replacement = rep("Rmd",5)
)
```
```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = "[Rr][Mm][Dd]",
  replacement = "Rmd"
)
```
```{r}
emailContent <- '親愛的_name_朋友好，恭喜你，你的電子發票號碼_invoiceNumber_ 差點中獎。'
cat(emailContent)
```
```{r}
replacementNamedVector <- c(
  "_name_" = "小新",
  "_invoiceNumber_" = "EF-89400133"
)

synthesizedContent <- str_replace_all(
  emailContent,
  replacementNamedVector
)
cat(synthesizedContent)
```
```{r}
set.seed(2020)
d1 <- sample(c(rep("4",10),rep("3",3),rep("7",3)), 25, replace=T)
d2 <- sample(98:109, 25, replace=T)
d3 <- sample(c("73", "74", "78", "83", "72"))
d4 <- sample(1:120, 25, replace=T)
d4 <- str_pad(d4, 3, side = "left", pad="0")
schoolIds <- paste0(d1,d2,d3,d4)
schoolIds
```
```{r}
# {x} 前方卷帶連裝x條
str_subset(schoolIds,
           pattern='[0123456789]{9}')
str_subset(schoolIds,
           pattern='[0-9]{9}')
str_subset(schoolIds,
           pattern='[:digit:]{9}')
```
```{r}
myLove2R <- c("我實在是太愛太愛太愛愛R課程了",
  "我才是太愛太愛太太愛太太太愛R了",
  "我則是太愛愛太愛太愛愛愛R了",
  "找我太太聊天，我太太愛理不理的，我只好回去練我最愛的R。")
```
```{r}
str_view_all(myLove2R, "(太愛){2}")
```
```{r}
# {1,2} 前面卷帶裝1～2條 
str_view_all(myLove2R, "太[愛]{1,2}")
str_view_all(myLove2R, "太愛{1,2}") # 卷帶只有一個字，可不寫[]

# ? 前面卷帶不確定要不要裝（要裝也只會裝1條）
str_view_all(myLove2R, "太愛[愛]?")
```
```{r}
str_view_all(myLove2R, "太[愛]+")
```
```{r}
str_view_all(myLove2R, "太[愛]*")
```
```{r}
str_view_all(myLove2R, "太愛[愛]?")
```
```{r}
str_view_all(myLove2R, "太+愛+")
```
```{r}
str_view_all(myLove2R, "太+愛+(?!理不理)")
```
```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')
str_extract(
  addresses,
  "(?<=[縣市])[\u4E00-\u9FFF]+[區鎮]"
)
```
```{r}
str_extract(
  addresses,
  "(?<=[縣市])[^區]+[區鎮]"
)
```
```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")
str_subset(
  Rmdfiles, "[Rr][Mm][Dd]"
)

# 要求在句尾
str_subset(
  Rmdfiles, "[Rr][Mm][Dd]$"
)
```
```{r}
download.file("https://www.dropbox.com/s/o9kt3lxtx9pmjqj/homework2.Rmd?dl=1", destfile = "./hw2.Rmd", mode="wb")
xfun::read_utf8("./hw2.Rmd") -> hw2lines
View(hw2lines)
```
```{r}
pick_starting3Hash <- str_detect(
  hw2lines,
  "^###"
)
sum(pick_starting3Hash)
```
```{r}
pick_starting3Hash <- str_detect(
  hw2lines,
  "^### (?=[0-9])"
)
sum(pick_starting3Hash)
```
```{r}
library(purrr)
```
```{r}
sukiyaMenu <- jsonlite::fromJSON("https://www.dropbox.com/s/iu9b1hnvbtss83q/sukiyaMenu.json?dl=1")

nonsetMenu3 <- sukiyaMenu[c("豪華雙饗丼", "牛丼類", "咖哩類" )]
```
```{r}
items <- list()
items$dish_name = vector("list", length=3)
```
```{r}
# 餐點名稱
dish_name = nonsetMenu3[[1]]$name
items$dish_name[[1]] <- unlist(dish_name)

dish_name = nonsetMenu3[[2]]$name
items$dish_name[[2]] <- unlist(dish_name)

dish_name = nonsetMenu3[[3]]$name
items$dish_name[[3]] <- unlist(dish_name)
```

